[greeter]
theme-name = Win11-dark
icon-theme-name = Win11-dark
background = /usr/share/backgrounds/dizdar_wallpaper.jpg
user-background = false
font-name = Sans 10
xft-antialias = true
xft-dpi = 96
xft-hintstyle = hintslight
xft-rgba = rgb
indicators = ~host;~spacer;~clock;~spacer;~session;~language;~power
position = 50%,center 50%,center
default-user-image = /usr/share/icons/Win11-dark/places/64/user-info.svg
screensaver-timeout = 60
