#!/bin/sh

set -e

lb config noauto \
    --mode "debian" \
    --initsystem "systemd" \
    --distribution "bookworm" \
    --debian-installer "false" \
    --archive-areas "main contrib non-free non-free-firmware" \
    --iso-volume "Dizdar Linux Live" \
    --iso-publisher "Dizdar Linux Project" \
    --iso-application "Dizdar Linux" \
    --binary-images "iso" \
    --memtest "none" \
    --apt-indices "false" \
    --apt-recommends "true" \
    --bootappend-live "boot=live components quiet splash locales=tr_TR.UTF-8 keyboard-layouts=tr username=dizdar user-password=dizdar hostname=dizdar-linux plymouth.ignore-serial-consoles" \
    --security "false" \
    "${@}"

