#!/bin/sh

set -e

lb config noauto \
    --mode "debian" \
    --distribution "bookworm" \
    --debian-installer "live" \
    --debian-installer-distribution "bookworm" \
    --archive-areas "main contrib non-free non-free-firmware" \
    --iso-volume "Dizdar Linux Live" \
    --iso-publisher "Dizdar Linux Project" \
    --iso-application "Dizdar Linux" \
    --binary-images "iso" \
    --memtest "none" \
    --apt-indices "false" \
    --apt-recommends "true" \
    --bootappend-live "boot=live components quiet splash plymouth.ignore-serial-consoles" \
    --debootstrap-options "--keyring=/usr/share/keyrings/debian-archive-keyring.gpg" \
    "${@}"
